### ISSUE TITLE
Style Guide & Common Terms

### ISSUE THREAD

**Issue by regalius** [reactjs/id.react.dev#2]
# UPDATE: 👉 Please Check out the [Glossary](https://github.com/reactjs/id.reactjs.org/wiki/Glosarium) and [TRANSLATION.md](https://github.com/reactjs/id.reactjs.org/blob/master/TRANSLATION.md) file

Hi @reactjs/reactjs-org-indonesian-translation ,

Before more contributors joined, I think we need to:
1. Start building our style guide
2. Agreed upon common diction/terms that we'll choose

Perhaps, we need a [TRANSLATION.md](https://github.com/reactjs/ja.reactjs.org/blob/master/TRANSLATION.md) like our Japanese counterpart.

**Comment by gedeagas** [comment]
**Common Terms**
re-render --> 
arrow function  -->
template literals  -->
controlled component  -->
uncontrolled component  -->
props  -->
state  -->
camelcase  -->
lowercase  -->
callback  -->
event handler  -->

**Comment by regalius** [comment]
I propose the following diction:

re-render --> render ulang

This terms can be either kept in English or translated to Bahasa (Me personally prefer them to be in english since it is easier to understand):
controlled component --> Komponen terkontrol
uncontrolled component --> Komponen tak terkontrol

The other terms I think would be easier for readers if it stays in english because it'll be a little bit weird if it translated into standardized Bahasa:
arrow function --> ??
event handler --> pengurus even ?

**Comment by gedeagas** [comment]
i agree with you @regalius, sometimes literal translation can be little bit weird if it translated into standardized Bahasa. so for those word i think we should keep it as is. 

controlled component --> Komponen terkontrol
uncontrolled component --> Komponen tak terkontrol

for these word, i also prefer them in english. 
But, if we want to make translation for people who doesn't speak english that well would they understand the meaning of these word ?.  

@arfianadam do you have other opinion ?

**Comment by arfianadam** [comment]
The point of having a localized documentation is to have _more_ people understand the contents _better_. Indeed there are a lot of terms that were already familiar and easier to understand in English. But, we can't throw away the fact that there might be still many people who don't understand those terms.

So the solution would be, if the literal translation of those terms sound weird or even harder to understand, first we must try to think if there is better words to replace the literal translation. _Then_ if we can't find the replacement, we may use the English word instead. Note that we can't just put English words here just because it's hard to translate them.

Since it's undeniable that there _will_ be not translated English words, we can come up with a separate Glossary page that explains those might-be-hard-to-understand terms. Can we do that @tesseralis ?

**Comment by tesseralis** [comment]
@arfianadam There's already a glossary in the docs: https://reactjs.org/docs/glossary.html It might be a good idea to do that first :)

One thing I've seen people do is use the english term but put the translated term in parentheses the first time it's mentioned.

**Comment by arfianadam** [comment]
Let's track the progress of those terms' translation here. Later when we are ready to publish it we should update https://github.com/reactjs/id.reactjs.org/blob/master/CONTRIBUTING.md so that contributors can know the decision. I've edited @gedeagas 's [comment](https://github.com/reactjs/id.reactjs.org/issues/2#issuecomment-461676901) to track the progress.

**Comment by regalius** [comment]
Several things that I noticed after translating the Homepage,

About Component/Komponen stuff. I think it makes more sense to keep it as it is for:
- controlled component
- uncontrolled component
- stateful component
- stateless component

But for standalone `Component` we can just translate it to `Komponen`, later we can have some kind of glossary that explains it in Bahasa just like [訳語の統一](https://github.com/reactjs/ja.reactjs.org/wiki/%E8%A8%B3%E8%AA%9E%E3%81%AE%E7%B5%B1%E4%B8%80) in Japanese Translation repo.

The other thing that I noticed is about our style guide on when we should italicize a foreign terms? I think we should italicize them when it is part of a paragraph only (not in the header)

**Comment by gedeagas** [comment]
@regalius in my opinion, loanwords only need to be italicized when it is part of a paragraph only.

**Comment by martinock** [comment]
Hi, should we translate "Functional Component" into "Komponen Fungsional" or just let it be "Functional Component"?

PS*: Also asking for "Class Component"

**Comment by regalius** [comment]
In my opinion, for now, I think let's keep them in English @martinock, later if we find the needs to translate the whole * Component, we can do it easier.

**Comment by regalius** [comment]
I've added @gedeagas 's comment to the [glossary](https://github.com/reactjs/id.reactjs.org/wiki/Glosarium), feel free to improve it!

**Comment by mendoanjoe** [comment]
try using this ? [I.G.3.](https://puebi.readthedocs.io/en/latest/huruf/huruf-miring/) @martinock

**Comment by gedeagas** [comment]
@regalius @arfianadam 

| English | Indonesian |
| ------ | ------ |
| eparates concerns | memisahkan kepentingan |


gimana ?

**Comment by arfianadam** [comment]
@gedeagas contoh konteks kalimatnya seperti apa? Sekilas benar tapi kok jadi kepikiran kalau di konteks tertentu mungkin bisa berubah arti.

**Comment by mnindrazaka** [comment]
how about `Fragment`, should we translate it to `Pecahan` ?

**Comment by mazipan** [comment]
| English        | Indonesian |
| ------------- |:-------------:|
| package      | paket | 

Based on this PR: https://github.com/reactjs/id.reactjs.org/pull/11/files, line 13

**Comment by aisy** [comment]
How about key? should be like this?
| English  | Indonesian |
| key  | _key_  |

**Comment by mazipan** [comment]
@aisy: Pilihannya antara kita pertahankan istilah dalam bahasa inggris, tapi dengan italic.
Atau kita translate secara harafiah.

Tapi bisa juga kita sertakan keduanya agar pembaca bisa memahami konteks aslinya, ex: Kunci (*key*)

**Comment by arfianadam** [comment]
@mnindrazaka @mazipan kedua kata tersebut lebih baik dipertahankan dalam Bahasa Inggris. _Fragment_ dan _package_.

**Comment by mazipan** [comment]
Yang penting konsisten sih mas @arfianadam, jangan ada yang gonta-ganti.

**Comment by regalius** [comment]
Agreed mas @arfianadam

**Comment by regalius** [comment]
@aisy `key` is fine mas, because I think it is a React specific term

**Comment by TitusEfferian** [comment]
halo, saya menghadapi beberapa kosa kata serapan yang jika diterjemahkan kedalam bahasa indonesia menjadi lebih rancu, dikarenakan biasanya juga dalam studi maupun jurnal tetap menggunakan serapan

contoh:
`class`
`public` (access modifier)
`bind` / `binding`
`listeners`

apakah harus diterjemahkan, atau dapat di cetak miring saja?

**Comment by regalius** [comment]
Hi mas @TitusEfferian,

class -> kelas
public -> publik

bind -> *bind*
(event) listener -> (event) *listener*

publik and kelas is acceptable enough I think 😄 

For example:

Untuk membuat sebuah komponen baru, kita akan membuat sebuah kelas, kelas tersebut akan bersifat publik. Setelah komponen dibuat sebuah *event listener* akan kita *bind* ke komponen tersebut agar komponen dapat menerima *event*

**Comment by regalius** [comment]
Mas @gedeagas , `separates concerns` as in `memisahkan kepentingan` is OK to be translated, while `Separation of Concerns(SOC)` I think is better to be not translated as it is common engineering term. CMIIW

**Comment by TitusEfferian** [comment]
so, how about this sentences? 
`public class fields syntax`
do i need to translate to :
 `sintaksis bidang kelas publik`?
@regalius

**Comment by regalius** [comment]
@TitusEfferian IMO, `If you are using the experimental public class fields syntax` -> Jika anda menggunakan sintaks eksperimental `public class fields`, because public class fields in this case is the name of the sintaks itself :smile:

**Comment by gedeagas** [comment]
Awesome @regalius

**Comment by mnindrazaka** [comment]
any suggestion for `shallow comparison` ? should it translate to `perbandingan dangkal`

**Comment by spondbob** [comment]
Noticed inconsistency translation for `Importing` on these 2 PRs #16  and #18 (`Pengimporan` vs `Mengimpor`).
I feel like the context here is trying to say `Cara Menggunakan` as in how to use the syntax, or how to load it into your environment if that makes sense.

| English  | Indonesian |
| ------------- | ------------- |
| Importing (How to import)  | Cara Menggunakan  |

When someone approved and added this translation to [glossary](https://github.com/reactjs/id.reactjs.org/wiki/Glosarium), could you order it by alphabet please?

Also let's try to avoid asking translations on this issue so that it keeps clean with glossary suggestions. No harm opening up a new issue if you find it hard to come up with one. And once you got your translation you can always link your issue back here to be added to glossay. Just my two cents :thumbsup:

**Comment by martinock** [comment]
While translating tutorial page, I found some term that are not in glossary yet and come up with suggestion: 
`mutable` --> `mutable`
`immutable`  --> `immutable`
`immutability`--> `immutability`
`object tree`  --> `pohon objek`

I suggest we add these keyword to glossary. What do you think?

**Comment by regalius** [comment]
@spondbob I do agree about the context of `Importing` for these 2 PRs are `Cara menggunakan`, do you mind to leave your comments to these PRs also?

About the alphabetic glossary, yep, I'll arrange them in alphabetic order since it has grown quite big

About asking the translations on this issue, I think it's fine if you want to ask them here or create a new issue, in the end, our source of truth should be on the [glossary](https://github.com/reactjs/id.reactjs.org/wiki/Glosarium) so you might not need to check terms out here, since it'll be easier to check the glossary instead 😄

**Comment by spondbob** [comment]
Cheers @regalius, sure will leave a comment there.

On a second thought, `Cara Import` more straightforward than `Cara Menggunakan` cause `Cara Menggunakan` may imply how to use the API itself or how to use it as an example.

**Comment by riandy-dimas** [comment]
Is it okay to put `higher-level API` as it is? Kinda weird to translate it into `API tingkat atas / API tingkat tinggi`.

**Comment by regalius** [comment]
Hmm, `API tingkat atas` is, I personally think *somewhat* fine, What do you think guys @arfianadam @gedeagas ?

**Comment by resir014** [comment]
HI @regalius, I've taken my time to set up a [TRANSLATION.md](https://github.com/resir014/id.reactjs.org/blob/translation.md/TRANSLATION.md) file like our Japanese counterpart, which also hosts the translated version of the Universal Style Guide. I've also opened PR #20 to add it here.

**Comment by regalius** [comment]
Nice, thanks @resir014 👍

**Comment by arfianadam** [comment]
@regalius `*API* tingkat atas` is fine I think.

**Comment by RiskyFeryansyahP** [comment]
how about **subscription** ? should i translate it to **Berlangganan** or keep *subscription* with italic ?

**Comment by regalius** [comment]
Hmm can you give the full sentence @RiskyFeryansyahP ? 😄  Generally I think it'll be better to translate it as Berlangganan but, let's see from the context of the sentence itself

**Comment by grikomsn** [comment]
Here's an example from what I'm currently working on **Hooks at a Glance**, emphasis mine:

> ...for example, this component uses an effect to **subscribe** to a friend's online status, and cleans up by **unsubscribing** from it.

Can be roughly translated to this:

> ...sebagai contoh, komponen berikut menggunakan sebuah efek untuk ***subscribe*** kepada status online teman, dan membersihkan dengan ***unsubscribe*** darinya.

Or maybe this:

> ...sebagai contoh, komponen berikut menggunakan sebuah efek untuk **berlangganan** kepada status online teman, dan membersihkan dengan **berhenti berlangganan** darinya.

**Comment by grikomsn** [comment]
Also, what does `lifecycle` translates to? Example sentences:

- React state and lifecycle features -> _state_ dan fitur-fitur _lifecycle_ React
- Class lifecycles -> _lifecycle_ kelas
- Lifecycle methods -> _method lifecycle_ / metode-metode _lifecycle_

**Comment by spondbob** [comment]
Just thinking out loud here:

> ...this component uses an effect to subscribe to a friend's online status, and cleans up by unsubscribing from it.

> ...komponen berikut menggunakan sebuah efek untuk (menerima/memperoleh) status online teman, dan menghentikan (efek/proses) tersebut setelahnya.

Here we know that by **subscribe** means it is continually receiving data, so I reckon it is safe to say *menerima/memperoleh* than *berlangganan* which in my head is more like for *subscribing papers*. And you can possibly add *menerima/memperoleh **secara terus menerus*** to emphasize the meaning. Same idea with **unsubscribe**, using the synonyms to fit in Indonesian.

As for **lifecycle** you can try *siklus*:

* React state and lifecycle features -> Fitur-fitur *state* dan siklus React **OR** Fitur-fitur React seperti *state* dan siklus (It seems **features** is a noun for **state** and **lifecycle**. Not sure with the rest of sentence where it could possibly be a verb.)
* Class lifecycles -> Siklus kelas
* Lifecycle methods -> (metode/fungsi) siklus

Another form would be *tahapan-tahapan*. Try to find the synonyms if it fits well than a direct translation.

With that, is it worth it to link the Glossary somewhere in the doc/website where we can explain more about the terms used? If we have that we can keep using the English form and in someway link it to Glossary for readers to understand it. For examples:

* subscribe: Proses menerima data secara terus menerus atau kontinu.
* lifecycle: Rangkaian proses yang terjadi secara berurutan. Sebagai contoh *component lifecycles* -> siklus komponen React yang dimulai dari componentWillMount bla bla bla

I don't know if other languages doing that way. Otherwise just translate it as close as to our audience.

**Comment by RiskyFeryansyahP** [comment]
> Just thinking out loud here:
> 
> > ...this component uses an effect to subscribe to a friend's online status, and cleans up by unsubscribing from it.
> 
> > ...komponen berikut menggunakan sebuah efek untuk (menerima/memperoleh) status online teman, dan menghentikan (efek/proses) tersebut setelahnya.
> 
> Here we know that by **subscribe** means it is continually receiving data, so I reckon it is safe to say _menerima/memperoleh_ than _berlangganan_ which in my head is more like for _subscribing papers_. And you can possibly add _menerima/memperoleh **secara terus menerus**_ to emphasize the meaning. Same idea with **unsubscribe**, using the synonyms to fit in Indonesian.
> 
> As for **lifecycle** you can try _siklus_:
> 
> * React state and lifecycle features -> Fitur-fitur _state_ dan siklus React **OR** Fitur-fitur React seperti _state_ dan siklus (It seems **features** is a noun for **state** and **lifecycle**. Not sure with the rest of sentence where it could possibly be a verb.)
> * Class lifecycles -> Siklus kelas
> * Lifecycle methods -> (metode/fungsi) siklus
> 
> Another form would be _tahapan-tahapan_. Try to find the synonyms if it fits well than a direct translation.
> 
> With that, is it worth it to link the Glossary somewhere in the doc/website where we can explain more about the terms used? If we have that we can keep using the English form and in someway link it to Glossary for readers to understand it. For examples:
> 
> * subscribe: Proses menerima data secara terus menerus atau kontinu.
> * lifecycle: Rangkaian proses yang terjadi secara berurutan. Sebagai contoh _component lifecycles_ -> siklus komponen React yang dimulai dari componentWillMount bla bla bla
> 
> I don't know if other languages doing that way. Otherwise just translate it as close as to our audience.

i think it's a good idea using menerima/memperoleh

**Comment by lunmay** [comment]
I have several suggestions for the existing [Glosarium](/reactjs/id.reactjs.org/wiki/Glosarium) entries:

| English | Indonesian | Suggestion | Comment |
|-|-|-|-|
| export | eksport  | ekspor (n), mengekspor (v) | I don't understand why it ends with 't'. in the original entry
| import | import  | impor (n), mengimpor (v) | Ditto
| mobile phone | telepon seluler | ponsel | Shorter is always better, no?
| mount | pasang | kait (v) | Rather than the general 'pasang', let's narrow its meaning here. For example: "componentDidMount() akan langsung dijalankan setelah komponen dikaitkan (disisipkan ke pohon)"
| package | package | paket (n)| Except as keyword, let's use it just like other paket in other worlds, shall we?
| plugin | *plugin* | plugin (n) | Just absorb it. No need to italicize it.
| render | *render* | render (v) | Just absorb it. See *rendering* for the noun. Verb is simply 'merender'
| rendering | *rendering* | proses render | We can always call it perenderan, but...

**Comment by regalius** [comment]
> ...sebagai contoh, komponen berikut menggunakan sebuah efek untuk **berlangganan** kepada status online teman, dan membersihkan dengan **berhenti berlangganan** darinya.

@grikomsn I think in this sentence I personally prefer `berlangganan` because it sounds more fluid rather than `subscribe`, What do you think?

For `lifecycle`, I personally prefer to just keep it as *lifecycle* since it sounds more familiar also agreed with @spondbob that we might have a glossary later to explain the English form to the readers for easier understanding

**Comment by grikomsn** [comment]
The word `berlangganan` seems okay, but if used on a sentence like `data subscription -> (ber)langganan data` sounds weird, IMO.

And `lifecycle` is somewhat better sounding than `siklus`. Should I revert my commit or something, @regalius?

**Comment by regalius** [comment]
@lunmay , I'd try to explain each of the entry and the decision making behind it as best as I could.

- **export & import** - Both `eksport` and `ekspor` are valid in KBBI see [here](https://kbbi.kemdikbud.go.id/entri/eksport) and [here](https://kbbi.kemdikbud.go.id/entri/ekspor) so both of them can be used
- **mobile phone** - We decided to go with more verbosity rather than the acronym hence `telepon seluler` @gedeagas can explain more about this 😄 
- **mount** - Hmm, I personally think that `kait` would closely translated to `to hook` rather than `to mount` and `sisip` would be closer to `to insert` than `to mount`, what do you think guys?
- **package** - We think *package* would be more familiar to the ears of the readers if we talk about software dependency rather than `paket` for example: 
 > ".. Anda dapat memasang React dengan mengunduh paketnya terlebih dahulu`

 > ".. Anda dapat memasang React dengan mengunduh *package*nya terlebih dahulu"
- **plugin & render** - Both plugin and render are not official Indonesian language that's why we need to italicize it, we determine if we should italicize think based on if we could find it on [KBBI](https://kbbi.kemdikbud.go.id)

CMIIW 😄

**Comment by goFrendiAsgard** [comment]
I can't find the correct translation for `pass an event handler`. Based on the glosarium, I should translate it into `mengoperkan sebuah event handler`. IMO It doesn't sound right. Any opinion on this?

**Comment by imiro** [comment]
Hi! I stumbled upon some terms that might be good to be added to the Glossary. I've written down my own suggestions for them.

| **English** | **Indonesian** suggestion | **Comments**
|---|---|---
| Refactor | menuliskan ulang, menuliskan kembali | 
| Web | _web_, jaringan | As in _web app_, is it better to use `aplikasi web` or `aplikasi jaringan` ?
| Mouse | tetikus | I think both `tetikus` and `kursor` could be used in this case
| Cursor | kursor | 
| Encapsulate | merangkum / mengenkapsulasi | Google's Indonesian Translation for encapsulates is `merangkum`, but it does not sound convincing? I personally prefer meng-enkapsulasi, what do you guys think?

Also, I noticed that `listener` has been included in the glossary to be used as is (italicized), but how about this sentence?

... `<Mouse>` component encapsulates all behavior associated with listening for `mousemove` events ...

Should it translates to:

komponen `<Mouse>` mengenkapsulasi semua perilaku yang terkait dengan me-_listen_ kepada _event_ `mousemove` ?

**Comment by wisn** [comment]
@imiro, as for `encapsulate`, use `mengenkapsulasi` instead of `merangkum`. It is more like term so translate it literally makes it weird.

**Comment by resir014** [comment]
@imiro @wisn The glossary has been updated with your suggestions. Thanks!

**Comment by asharimh97** [comment]
Hi, I got stuck in deciding how to translate **development build** or **production build**. We could translate **development** as pengembangan and **production** as produksi, **build** could be translated as **pembangunan**

But when it comes to **development builds**, will it be like **pembangunan pengembangan**? Somehow I don't feel confident about this word.

**Comment by andriawan** [comment]
@asharimh97 i think the phrase **development build** or **production build** doesn't need to translate literally. just write as is with italic style. Maybe you want to propose as new glossary item as i check, it doesn't include on glossary.

**Comment by resir014** [comment]
@asharimh97 

> But when it comes to development builds, will it be like pembangunan pengembangan? Somehow I don't feel confident about this word.

Probably a more suitable compromise: ***build* pengembangan** (for development build) and ***build* produksi** (for production build).

@grikomsn @rizafahmi any thoughts?

**Comment by spondbob** [comment]
Jumping in here for @asharimh97 's query, I'd say 2 options:
1. For translation I would suggest **versi pengembangan** and **versi produksi** looking at both context ie. _Remember that you only need to do this for production builds_ would be _Perlu diingat hal ini cukup diaplikasikan untuk versi produksi_.
2. Else, second @resir014 's with having it italicize in english and potentially explain the term somewhere in Glossary.

Both depends on maintainer's direction on how we want to represent Indonesian doc version - fully proper local translation VS semi. Might worth looking at other languages how they approach such issue.

**Comment by resir014** [comment]
@spondbob I agree with using **versi pengembangan** and **versi produksi** for those terms. Let's go with that!

I'm also adding one more suggestion after reading through the RSNI:

| English | Indonesian     |
| ------- | -------------- |
| tree    | diagram, bagan |

We currently have these translated to "pohon" in some pages, but since "tree" in many of these contexts refers to the diagram of things (i.e. DOM tree), we might as well standardise these terms as such.

**Comment by paramithatm** [comment]
Hi, I want to ask what's the proper translation for `feature flags` ? Is it `bendera fitur` or `_flag_ fitur`

Also, can we strive for consistency for words like `project -> proyek` and `object -> obyek` , since there's still some translated pages that uses `objek` and `projek`.
I also found some typo in pages. If it's alright can I make a different PR to fix them?

**Comment by resir014** [comment]
@paramithatm Sure, pull requests for spelling consistencies are always welcome!

**Comment by resir014** [comment]
Also, to reference @grikomsn's comment [here](https://github.com/reactjs/id.reactjs.org/pull/53#discussion_r302008774):

The section on Hooks sees some similar paragraphs describing Hooks, but various contributors have their own version of translation. Here are PR diffs related to Hooks:

- [Diff for Using the State Hook](https://github.com/reactjs/id.reactjs.org/pull/28/files#diff-6024d880e5eef39cfbff54653ef34fb6R9) (#28):

  ```diff
  - *Hooks* are a new addition in React 16.8. They let you use state and other React features without writing a class.
  + *Hooks* merupakan fitur baru di React 16.8. Fitur ini memungkinkan Anda menggunakan *state* dan fitur React lainnya tanpa menuliskan sebuah kelas.
  ```

- [Diff for Using the Effect Hook](https://github.com/reactjs/id.reactjs.org/pull/38/files#diff-25b65c3d9aaad3771cfbb8ac2f5361b4R9) (#38):

  ```diff
  - *Hooks* are a new addition in React 16.8. They let you use state and other React features without writing a class.
  + *Hooks* adalah tambahan baru di React 16.8. *Hooks* memungkinkan Anda dapat menggunakan *state* dan fitur lain di *React* tanpa menulis *class*.
  ```

- [Diff for Hooks at a Glance (merged)](https://github.com/reactjs/id.reactjs.org/pull/88/files#diff-9bda51acb98cffd656661def0255b05bR9) (#88):

  ```diff
  - *Hooks* are a new addition in React 16.8. They let you use state and other React features without writing a class.
  + *Hooks* merupakan penambahan baru pada React 16.8. *Hooks* memungkinkan Anda menggunakan *state* dan fitur React lainnya tanpa membuat sebuah kelas.
  ```

- [Diff for Rules of Hooks (merged)](https://github.com/reactjs/id.reactjs.org/pull/53/files#diff-ca7f854fc975bddf46b31cc423b07428R9) (#53)

  ```diff
  - *Hooks* are a new addition in React 16.8. They let you use state and other React features without writing a class.
  + *Hooks* merupakan fitur baru di React 16.8. Fitur ini memungkinkan Anda menggunakan *state* dan fitur React lainnya tanpa menuliskan sebuah kelas.
  ```

To make these consistent, I propose we change them all to this:

```
*Hooks* merupakan fitur baru pada React 16.8. *Hooks* memungkinkan Anda menggunakan *state* dan fitur React lainnya tanpa membuat sebuah kelas.
```

**Comment by tegarjgap** [comment]
Hi I want to ask, **The reconciler** is term of english and how can I write this word? better *The reconciler* or just *reconciler*?

thanks

**Comment by andriawan** [comment]
how we translate higher-order components in bahasa? should it be translated or leave it as is?

**Comment by lunmay** [comment]
> 
> 
> how we translate higher-order components in bahasa? should it be translated or leave it as is?



> 
> 
> @spondbob I agree with using **versi pengembangan** and **versi produksi** for those terms. Let's go with that!
> 
> I'm also adding one more suggestion after reading through the [RSNI](https://github.com/jk8s/sig-docs-id/raw/master/resources/RSNI-glossarium.pdf):
> English 	Indonesian
> node 	simpul, _node_
> tree 	diagram, bagan
> 
> We currently have these translated to "pohon" in some pages, but since "tree" in many of these contexts refers to the diagram of things (i.e. DOM tree), we might as well standardise these terms as such.

Call me old school, but I don't think we can translate DOM tree as "diagram DOM".  It should stay as "pohon DOM", with its "root", induk, and anak.
Leave diagram/chart for all things you can draw, e.g. for various graphical charts terminology: flow charts, ERD, etc.

**Comment by lunmay** [comment]
> 
> 
> @asharimh97
> 
> > But when it comes to development builds, will it be like pembangunan pengembangan? Somehow I don't feel confident about this word.
> 
> Probably a more suitable compromise: **_build_ pengembangan** (for development build) and **_build_ produksi** (for production build).
> 
> @grikomsn @rizafahmi any thoughts?

How can you translate "build version" then?
"Build" *is* the result. "version" is *the name* you give for one of those result. 
Just leave build in italic.  _build_ pengembangan and _build_ produksi are fine for those.

**Comment by resir014** [comment]
> "Build" is the result. "version" is the name you give for one of those result.
> Just leave build in italic. build pengembangan and build produksi are fine for those.

@lunmay yes, I agree with this. Adding this to the glossary now. Let's try and replace all translations to match this.

**Comment by supercomputra** [comment]
@gedeagas I think "file" could be translatable as "berkas" without losing its context.
English | Indonesian
-- | --
file | berkas
