### ISSUE TITLE
Sharing State Between Components

### ISSUE THREAD

**Issue by zainfathoni** [reactjs/id.react.dev#381]
Page: https://id.react.dev/learn/sharing-state-between-components

Assignee: @yaffalhakim1

**Comment by yaffalhakim1** [comment]
hi mas @zainfathoni looks like i making a mistake in my PR [here](https://github.com/reactjs/id.react.dev/pull/370) because i still see my prev commit from my prev PR (which is merged). Do i need to create a new one or just continue the PR?

**Comment by zainfathoni** [comment]
It's up to you. If you know how to rebase your commits to the expected branch, you can keep this PR and "force push" your changes to it.

If you're not confident with it, you mau close this PR and raise a new one with the correct commits.

**Comment by yaffalhakim1** [comment]
> It's up to you. If you know how to rebase your commits to the expected branch, you can keep this PR and "force push" your changes to it.
> 
> If you're not confident with it, you mau close this PR and raise a new one with the correct commits.

I think I am fine with the first choice. Thank you, mas.
