### ISSUE TITLE
Synchronizing with Effects

### ISSUE THREAD

**Issue by zainfathoni** [reactjs/id.react.dev#389]
Page: https://id.react.dev/learn/synchronizing-with-effects

**Comment by adityaharist** [comment]
Hi, I’m interested in translating. Could you assign me to this one? Thanks

**Comment by mhaidarhanif** [comment]
@adityaharist You can open a Draft PR and inform here. Then it will be automatically assigned to you.

**Comment by hkohko** [comment]
is this page free? there doesn't seem to be anyone assigned to it.
