### ISSUE TITLE
`<Suspense>`

### ISSUE THREAD

**Issue by zainfathoni** [reactjs/id.react.dev#416]
Page: https://id.react.dev/reference/react/Suspense

Assignee: @maulanasdqn @chez14

**Comment by maulanasdqn** [comment]
thankyouu bang

**Comment by mhaidarhanif** [comment]
@maulanasdqn waiting for the Draft PR as well 👀 cc @r17x

**Comment by maulanasdqn** [comment]
sore ini beres bang baru mulai ngerjain xixixi @mhaidarhanif

**Comment by mhaidarhanif** [comment]
@maulanasdqn Can start with a simple Draft PR to confirm, doesn't have to be finished yet.

**Comment by chez14** [comment]
PR ready for review on #601.
