### ISSUE TITLE
Conditional Rendering

### ISSUE THREAD

**Issue by resir014** [reactjs/id.react.dev#431]
Page: https://id.react.dev/learn/conditional-rendering

**Comment by resir014** [comment]
Hi @rickyraz, are you still working on this page? If it's still in progress, don't forget to create a [draft Pull Request](https://github.com/reactjs/id.react.dev/blob/main/TRANSLATION.md?rgh-link-date=2023-05-01T05%3A01%3A55Z#pembuatan-draft-pull-request) so we can track your progress.

If you're unable to complete this page within the next day, let us know so we can reassign this issue to someone else.

**Comment by resir014** [comment]
Closed in #92.

**Comment by andriansanto** [comment]
@resir014 , I've opened a ready-to-review PR for this section's translation (https://github.com/reactjs/id.react.dev/pull/533) 🙏
