### ISSUE TITLE
`<textarea>`

### ISSUE THREAD

**Issue by zainfathoni** [reactjs/id.react.dev#433]
Page: https://id.react.dev/reference/react-dom/components/textarea

Assignee: @eriansha

**Comment by eriansha** [comment]
is this issue already picked up by someone? otherwise, i will take it

**Comment by mhaidarhanif** [comment]
@eriansha No one yet, you can take it by opening a Draft PR first, then inform it here.

By raising a Draft PR, we can assume that you're assigned to it automatically.
