### ISSUE TITLE
Queueing a Series of State Updates

### ISSUE THREAD

**Issue by resir014** [reactjs/id.react.dev#449]
Page: https://id.react.dev/learn/queueing-a-series-of-state-updates

Assignee: @milhamm

**Comment by milhamm** [comment]
Sorry, I didn't noticed it was taken

**Comment by mhaidarhanif** [comment]
@milhamm It was taken but not confirmed with a Draft PR by @mrevanzak yet. I think you can still take it.

**Comment by milhamm** [comment]
Ah sure thing, thanks

**Comment by mrevanzak** [comment]
sorry i forgot. so i cant contribute on this anymore?

**Comment by milhamm** [comment]
I'm open to hand it over to you if you want @mrevanzak
What do you think? @mhaidarhanif

**Comment by mhaidarhanif** [comment]
@mrevanzak @milhamm Depends on you two.

Some options:

1. If @milhamm want to give it back over to @mrevanzak , then @mrevanzak can take it back
2. If want to compare, you can both open a PR, then we'll compare it later which one to use based on the progress speed and result quality.

**Comment by milhamm** [comment]
I'm willing to take the first option. @mrevanzak you can start to create a draft PR. I will close mine in the mean time

Thanks for the suggestion @mhaidarhanif

**Comment by mrevanzak** [comment]
thanks sir @milhamm

**Comment by milhamm** [comment]
No worries, sorry for accidentally taking your part
