### ISSUE TITLE
`renderToStaticMarkup`

### ISSUE THREAD

**Issue by zainfathoni** [reactjs/id.react.dev#460]
Assignee: @lauslim12

**Comment by lauslim12** [comment]
Hi! Is there anyone working on this translation? If not, I'd be happy to help!

**Comment by mhaidarhanif** [comment]
@lauslim12 No one yet, you can help by opening a Draft PR first, then inform it here.

By raising a Draft PR, we can assume that you're assigned to it automatically.

**Comment by lauslim12** [comment]
I have made the PR in https://github.com/reactjs/id.react.dev/pull/505 👍
