### ISSUE TITLE
`renderToStaticNodeStream`

### ISSUE THREAD

**Issue by zainfathoni** [reactjs/id.react.dev#461]
Page: https://id.react.dev/reference/react-dom/server/renderToStaticNodeStream

Assignee: @rimamei

**Comment by rimamei** [comment]
Hello, I’m interested in translating. Can you assign me to this issue? cc @zainfathoni @resir014

**Comment by zainfathoni** [comment]
By raising a Draft PR, we can assume that you're assigned to it automatically.

Therefore, please raise a Draft PR with a very minimum change (one-line change is enough) at your earliest convenience. 😁

**Comment by rimamei** [comment]
Thank you for the explanation. So, this is my PR and it's ready to review https://github.com/reactjs/id.react.dev/pull/476
