### ISSUE TITLE
`Children`

### ISSUE THREAD

**Issue by resir014** [reactjs/id.react.dev#546]
Page: https://id.react.dev/reference/react/Children

**Comment by chez14** [comment]
Hi @resir014,

I'd like continue @ilham89's effort on translating this page, please let me know if it is okay to do so, or let me know if we need to prioritize certain pages.

Thank you!

**Comment by chez14** [comment]
I'll took the liberty of taking over this issue since it was labelled as `medium-priority` and no one currently actively working on this issue yet (last activity > 2 weeks). 

Please let me know if I shouldn't do so.
