### ISSUE TITLE
Rules of React - Components and Hooks must be pure

### ISSUE THREAD

**Issue by resir014** [reactjs/id.react.dev#652]
Page: [id.react.dev/reference/rules/components-and-hooks-must-be-pure](https://id.react.dev/reference/rules/components-and-hooks-must-be-pure)

Assignee: @FelixFern

**Comment by FelixFern** [comment]
Hi @resir014, it seems like you assigned me to the wrong issue it should be #653

**Comment by FelixFern** [comment]
here are the PR that closes this issue: https://github.com/reactjs/id.react.dev/pull/666 @resir014
