### ISSUE TITLE
Rules of React - React calls Components and Hooks

### ISSUE THREAD

**Issue by resir014** [reactjs/id.react.dev#653]
Page: [id.react.dev/reference/rules/react-calls-components-and-hooks](https://id.react.dev/reference/rules/react-calls-components-and-hooks)

Assignee:

**Comment by FelixFern** [comment]
hi @resir014, I would like to help resolve this issue, can you please update the assignee to me ? thanks!

**Comment by FelixFern** [comment]
here are the PR https://github.com/reactjs/id.react.dev/pull/660, thank you
