### ISSUE TITLE
[Bug]: Github Icon was referring to react releases instead of this repository

### ISSUE THREAD

**Issue by fzn0x** [reactjs/id.react.dev#663]
### Summary

Is it intentional or a bug?

### Page

https://id.react.dev/

### Details

![Screenshot 2024-04-12 123110](https://github.com/reactjs/id.react.dev/assets/50759463/46642c8f-9e5f-4114-b11b-4813644472d3)
![Screenshot 2024-04-12 123058](https://github.com/reactjs/id.react.dev/assets/50759463/35ebeb7d-451e-4754-875c-bb008e76a5dd)

**Comment by r17x** [comment]
It's not a bug, because in https://react.dev is referred to GitHub Release page of "React".
