### ISSUE TITLE
Dev error: "Blog posts must include an author in the metadata, for RSS feeds"

### ISSUE THREAD

**Issue by Juanryhn** [reactjs/id.react.dev#709]
### Summary

When I run react web locally it returns an error like this

![image](https://github.com/reactjs/id.react.dev/assets/87475729/3bce9c9f-1b06-4907-8d66-b75dfb680ea4)

But when I ask other contributor they don't have error like me. But I think I know the error comes from.
It is from `src/content/blog/index.md`

![image](https://github.com/reactjs/id.react.dev/assets/87475729/b8ca883f-c8e7-4301-94c6-8a87c3d7dbbd)

This file doesn't have data for author, date and description that will check in file `rss.js`

### Page

https://id.react.dev/ || local

### Details

Is there something missing step ?

I just forked and clone the repo, then run yarn > yarn dev. And it return error that I mentioned in the summary

**Comment by resir014** [comment]
@Juanryhn This is a bug related to upstream `react.dev` project. Will raise an issue there so it could be fixed.

In the meantime, the workaround is to either push your changes in your branch and see how it looks via the preview link, or [remove this line](https://github.com/reactjs/id.react.dev/blob/main/src/pages/%5B%5B...markdownPath%5D%5D.js#L106) during development.

**Comment by Juanryhn** [comment]
> @Juanryhn This is a bug related to upstream `react.dev` project. Will raise an issue there so it could be fixed.
> 
> In the meantime, the workaround is to either push your changes in your branch and see how it looks via the preview link, or [remove this line](https://github.com/reactjs/id.react.dev/blob/main/src/pages/%5B%5B...markdownPath%5D%5D.js#L106) during development.

@resir014 Oh I see. But if I have solution for this error can I make a PR ? or just wait for other fix this error

**Comment by resir014** [comment]
> Oh I see. But if I have solution for this error can I make a PR ? or just wait for other fix this error

Best to wait for upstream to fix it.

**Comment by Juanryhn** [comment]
Ohh ya sure !, Thanks
